### PR TITLE
revoke session if server doesn't return token data

### PR DESCRIPTION
**Pull request by mvetoshkin**

### CODE REVIEW

**Comment by ryanfitz** [comment]
We need to be very careful when we revoke sessions. For example if a user cant connect to a network or if our server is down, with this pull request users would get logged out, even though they still have a valid account. The only time we want to revoke a session is when the user connects to our server and our server returns back with an explicit message saying to revoke the session, currently it uses a 401 to signal this.

**Comment by mvetoshkin** [comment]
how about this change?

**Comment by ryanfitz** [comment]
What are the 400 errors you are seeing? 400 errors are probably too generic to revoke a session, but maybe the server is returning some errors which should really be 401's as 400s.

I know I've seen this error where I still have a valid account, but when i fetch polls the auth header is somehow in a bad state. I'm thinking the bug might exist in [this function](https://github.com/nifti/CinchKit/blob/master/CinchKit/CinchKit.swift#L164) and / or [here](https://github.com/nifti/CinchKit/blob/master/CinchKit/CinchKit.swift#L31).

**Comment by mvetoshkin** [comment]
Bad HTTP authentication header format

**Comment by mvetoshkin** [comment]
i'm almost sure it happens when i start app after testing cinchkit.

**Comment by ryanfitz** [comment]
Ok so there is probably a bug with the access token data (its stored in the keychain currently in a really dumb way). Look at [here](https://github.com/nifti/CinchKit/blob/master/CinchKit/Client/CinchClient%2BAuth.swift#L48) I'm thinking token.type and / or token.refresh are invalid (maybe nil or some weird data). Can you try replicating this bug and inspecting what the headers are that are getting sent?

**Comment by mvetoshkin** [comment]
screen shot 2015-07-24 at 17 11 53

**Comment by mvetoshkin** [comment]
so i think server receives Authorization: 'Bearer rrrrrrrrrrreeeeeee.....'

**Comment by ryanfitz** [comment]
hah! Look at `access` and refresh` there. That has to be test data that is from a mocked response. Search the stubs and I bet you see that somewhere.

**Comment by ryanfitz** [comment]
[here](https://github.com/nifti/CinchKit/blob/master/CinchKitTests/CinchKitTestsHelper.swift) we [go](https://github.com/nifti/CinchKit/blob/master/CinchKitTests/CNHSessionsTests.swift) haha.

**Comment by mvetoshkin** [comment]
:) i know it goes from cinchkit testing.
start cinch-ios, sign in there.
then start testing cinchkit in the same simulator
then start cinch-ios again

**Comment by mvetoshkin** [comment]
normally user shouldn't get this bug

**Comment by ryanfitz** [comment]
Awesome, now we can replicate it. After we run these tests at the end of the tests lets revoke the sessions and it looks like the client shouldn't need any updates, just updates to the tests

**Pull request closed without merging**
